# Generated by Django 2.1.3 on 2018-11-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clonifyapp', '0002_auto_20181128_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artistaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clonifyapp.Artist'),
        ),
    ]
